default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  url: postgres://diaspora:diaspora@localhost:5432/diaspora_dev
test:
  <<: *default
  url: postgres://diaspora:diaspora@localhost:5432/diaspora_test
# production:
#   <<: *default
#   url: "<%= ENV['DATABASE_URL'] %>"
